export type AlarmType
  = | 'cameraConnectionTimeout'
    | 'cameraRecognitionError'
    | 'robotConnectionTimeout'
    | 'robotError'
    | 'gripperGraspError'
    | 'conveyorError'
    | 'plcConnectionTimeout'
    | 'binCapacityWarning'
    | 'binCapacityFull'
